services:
  - type: web
    name: springboot-webapp
    env: java
    plan: free
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/webapp-0.0.1-SNAPSHOT.jar"
    autoDeploy: true
